Enclosed volume harpoon object
BHoM/Versioning_Toolkit pull request #143
Opened 2021-03-05 19:49 UTC by BingWangUS

### NOTE: Depends on 

   
### Issues addressed by this PR

Closes #

### Test files

### Changelog

 - add a custom upgrader for HarpoonObject in CFD_Toolkit

### Additional comments

2021-03-05 20:13 UTC, BingWangUS commented
@BHoMBot check all

2021-03-11 20:56 UTC, FraserGreenroyd requested changes
Probably need to rebase to get the changes I put in with @michaelhoehn recently (apologies!). Suggested change is a bit cleaner and makes sure the `newVersion` gets a type upgrade regardless of whether it contains a key for `center` or not :smile:

We also need to add versioning for the deleted method to the JSON with the message we discussed :smile:

2021-03-11 20:56 UTC, FraserGreenroyd commented on BHoMUpgrader41/Converter.cs
> +            }
```suggestion
            if (newVersion.ContainsKey("Center") && newVersion["Centre"] != null)
            {
                    newVersion["_t"] = newVersion["_t"].ToString().Replace("HarpoonObject", "VolumeHarpoonObject");
                    newVersion.Add("Location", newVersion["Center"]);
            }
            else
                    newVersion["_t"] = newVersion["_t"].ToString().Replace("HarpoonObject", "SurfaceHarpoonObject");

            newVersion.Remove("Center");
```

2021-03-11 22:46 UTC, FraserGreenroyd commented
@BHoMBot check installer

2021-03-11 22:54 UTC, FraserGreenroyd commented
@BHoMBot check copyright compliance

2021-03-11 22:57 UTC, FraserGreenroyd commented
@BHoMBot check core

2021-03-11 22:58 UTC, FraserGreenroyd approved these changes
This works with the other PR and passes versioning.

2021-03-11 22:59 UTC, merged