Added upgrader for ContourLoadSet and UniformLoadSet
BHoM/Versioning_Toolkit pull request #157
Opened 2021-04-07 01:36 UTC by JosefTaylor

### NOTE: Depends on 

[BHoM PR 1229](https://github.com/BHoM/BHoM/pull/1229)
   
### Issues addressed by this PR

Closes #

### Test files

### Changelog

### Additional comments

2021-04-07 13:42 UTC, IsakNaslundBh commented on BHoMUpgrader42/Converter.cs
> +                    {
think you might need to add a `"_t", _fullPathToType_` here as well

2021-04-08 16:13 UTC, FraserGreenroyd requested changes

2021-04-08 16:13 UTC, FraserGreenroyd commented on BHoMUpgrader42/Converter.cs
> +                }).ToList();
This line needs indenting one extra indent to line up correctly with the bits above it.

2021-04-19 15:45 UTC, JosefTaylor commented
@BHoMBot check installer

2021-04-19 17:59 UTC, JosefTaylor commented
@BHoMBot check code-copyright

2021-04-19 18:04 UTC, JosefTaylor commented
@BHoMBot check copyright

2021-04-19 18:06 UTC, JosefTaylor commented
@BHoMBot check copyright-compliance

2021-04-19 18:08 UTC, JosefTaylor commented
@FraserGreenroyd would you mind dealing with the check-installer and code-copyright tests? They appear to be superseded by other tests, and I don't know how to trigger them or dismiss them.

2021-04-19 23:01 UTC, maryannewachter commented
@JosefTaylor Versioning does not appear to have worked for the contour load set (though it did for the uniform load set). I'm getting the generic "This is a magic component" message

![image](https://user-images.githubusercontent.com/58230980/115313615-76deaa80-a128-11eb-8611-63ff54cade6d.png)

2021-04-20 21:31 UTC, JosefTaylor commented
@FraserGreenroyd @IsakNaslundBh Could you please add your review and merge if satisfied? @maryannewachter has approved the RAM PR including the functionality of the migrated objects.

2021-04-22 23:32 UTC, maryannewachter approved these changes
Works per [review](https://github.com/BHoM/RAM_Toolkit/pull/183) of RAM_oM

2021-04-23 07:35 UTC, IsakNaslundBh commented
@BHoMBot check core

2021-04-23 07:38 UTC, merged