Support for LCA_Toolkit refactor
BHoM/Versioning_Toolkit pull request #163
Opened 2021-06-14 14:51 UTC by michaelhoehn

### NOTE: Depends on 

   
### Issues addressed by this PR

Closes #

### Test files

### Changelog

### Additional comments

2021-06-15 14:42 UTC, FraserGreenroyd requested changes
I think the JSON needs to change to the suggested.

2021-06-15 14:42 UTC, FraserGreenroyd commented on BHoMUpgrader42/Upgrades.json
> +      "BH.oM.LifeCycleAssessment.MaterialFragment.IEnvironmentalProductDeclaration": "This interface has been removed as changes to the EPD object have rendered this unnecessary.",
```suggestion
      "BH.Engine.LifeCycleAssessment.Compute.AcidificationPotential": "This method has been removed as EvaluateEnvironmentalProductDeclaration contains the same functionality.",
      "BH.Engine.LifeCycleAssessment.Compute.EutrophicationPotential": "This method has been removed as EvaluateEnvironmentalProductDeclaration contains the same functionality.",
      "BH.Engine.LifeCycleAssessment.Compute.DepletionOfAbioticResources": "This method has been removed as EvaluateEnvironmentalProductDeclaration contains the same functionality.",
      "BH.Engine.LifeCycleAssessment.Compute.DepletionOfAbioticResourcesFossilFuels": "This method has been removed as EvaluateEnvironmentalProductDeclaration contains the same functionality.",
      "BH.Engine.LifeCycleAssessment.Compute.GlobalWarmingPotential": "This method has been removed as EvaluateEnvironmentalProductDeclaration contains the same functionality.",
      "BH.Engine.LifeCycleAssessment.Compute.OzoneDepletionPotential": "This method has been removed as EvaluateEnvironmentalProductDeclaration contains the same functionality.",
      "BH.Engine.LifeCycleAssessment.Compute.PhotochemicalOzoneCreationPotential": "This method has been removed as EvaluateEnvironmentalProductDeclaration contains the same functionality."
```

2021-06-15 14:42 UTC, FraserGreenroyd commented
@BHoMBot check versioning

2021-06-15 14:44 UTC, FraserGreenroyd commented
@BHoMBot check versioning

2021-06-15 15:08 UTC, FraserGreenroyd commented
@BHoMBot check versioning

2021-06-15 16:35 UTC, FraserGreenroyd commented
@BHoMBot check versioning

2021-06-16 01:12 UTC, michaelhoehn commented
@BHoMBot check versioning

2021-06-16 10:20 UTC, FraserGreenroyd commented
@BHoMBot check versioning

2021-06-16 10:46 UTC, FraserGreenroyd commented
@BHoMBot check versioning

2021-06-16 11:36 UTC, FraserGreenroyd commented
@BHoMBot check versioning

2021-06-16 12:57 UTC, FraserGreenroyd commented
@BHoMBot check versioning

2021-06-16 14:37 UTC, michaelhoehn commented
@BHoMBot check versioning

2021-06-18 19:42 UTC, FraserGreenroyd commented
@BHoMBot check versioning

2021-06-18 20:07 UTC, FraserGreenroyd requested changes

2021-06-18 20:07 UTC, FraserGreenroyd commented on BHoMUpgrader42/Upgrades.json
> +      "BH.Engine.LifeCycleAssessment.Compute.PhotochemicalOzoneCreationPotential": "This method has been removed as EvaluateEnvironmentalProductDeclaration contains the same functionality."
```suggestion
      "BH.Engine.LifeCycleAssessment.Compute.PhotochemicalOzoneCreationPotential": "This method has been removed as EvaluateEnvironmentalProductDeclaration contains the same functionality.",
      "BH.oM.LifeCycleAssessment.MaterialFragment.SectorEnvironmentalProductDeclaration": "This object has been replaced with a single EPD object and a specific Type parameter.",
      "BH.oM.LifeCycleAssessment.MaterialFragment.IEnvironmentalProductDeclaration": "This interface has been removed as changes to the EPD object have rendered this unnecessary."
```

2021-06-18 20:08 UTC, FraserGreenroyd commented
@BHoMBot check versioning

2021-06-21 08:13 UTC, FraserGreenroyd requested changes

2021-06-21 08:13 UTC, FraserGreenroyd commented on BHoMUpgrader42/Upgrades.json
> +      "BH.oM.LifeCycleAssessment.MaterialFragment.IEnvironmentalProductDeclaration": "This interface has been removed as changes to the EPD object have rendered this unnecessary."
```suggestion
      "BH.oM.LifeCycleAssessment.MaterialFragment.IEnvironmentalProductDeclarationData": "This interface has been removed as changes to the EPD object have rendered this unnecessary."
```

2021-06-21 08:16 UTC, FraserGreenroyd commented
@BHoMBot check versioning

2021-06-21 08:27 UTC, FraserGreenroyd commented
@BHoMBot check versioning

2021-06-21 09:00 UTC, FraserGreenroyd commented
@BHoMBot check versioning

2021-06-21 09:45 UTC, FraserGreenroyd requested changes

2021-06-21 09:45 UTC, FraserGreenroyd commented on BHoMUpgrader42/Upgrades.json
> +      "BH.oM.LifeCycleAssessment.MaterialFragment.IEnvironmentalProductDeclarationData": "This interface has been removed as changes to the EPD object have rendered this unnecessary."
```suggestion
      "BH.oM.LifeCycleAssessment.MaterialFragments.SectorEnvironmentalProductDeclaration": "This object has been replaced with a single EPD object and a specific Type parameter.",
      "BH.oM.LifeCycleAssessment.MaterialFragments.IEnvironmentalProductDeclarationData": "This interface has been removed as changes to the EPD object have rendered this unnecessary."
```

2021-06-21 09:46 UTC, FraserGreenroyd commented
@BHoMBot check versioning

2021-06-21 10:26 UTC, FraserGreenroyd requested changes

2021-06-21 10:26 UTC, FraserGreenroyd commented on BHoMUpgrader42/Upgrades.json
> +      "BH.Engine.LifeCycleAssessment.Compute.AcidificationPotential": "This method has been removed as EvaluateEnvironmentalProductDeclaration contains the same functionality.",
```suggestion
      "BH.Engine.LifeCycleAssessment.Compute.AcidificationPotential(BH.oM.Dimensional.IElementM, BH.oM.LifeCycleAssessment.MaterialFragments.IEnvironmentalProductDeclarationData)": "This method has been removed as EvaluateEnvironmentalProductDeclaration contains the same functionality.",
"BH.Engine.LifeCycleAssessment.Compute.AcidificationPotential(System.Double, System.Double, System.Double)", "This method has been removed as EvaluateEnvironmentalProductDeclaration contains the same functionality.",
```

2021-06-21 10:26 UTC, FraserGreenroyd commented on BHoMUpgrader42/Upgrades.json
> +      "BH.Engine.LifeCycleAssessment.Compute.EutrophicationPotential": "This method has been removed as EvaluateEnvironmentalProductDeclaration contains the same functionality.",
```suggestion
      "BH.Engine.LifeCycleAssessment.Compute.EutrophicationPotential(System.Double, System.Double, System.Double)" : "This method has been removed as EvaluateEnvironmentalProductDeclaration contains the same functionality.",
"BH.Engine.LifeCycleAssessment.Compute.EutrophicationPotential(BH.oM.Dimensional.IElementM, BH.oM.LifeCycleAssessment.MaterialFragments.IEnvironmentalProductDeclarationData)" : "This method has been removed as EvaluateEnvironmentalProductDeclaration contains the same functionality.",
```

2021-06-21 10:26 UTC, FraserGreenroyd commented on BHoMUpgrader42/Upgrades.json
> +      "BH.Engine.LifeCycleAssessment.Compute.DepletionOfAbioticResources": "This method has been removed as EvaluateEnvironmentalProductDeclaration contains the same functionality.",
```suggestion
      "BH.Engine.LifeCycleAssessment.Compute.DepletionOfAbioticResources(System.Double, System.Double, System.Double)" : "This method has been removed as EvaluateEnvironmentalProductDeclaration contains the same functionality.",
"BH.Engine.LifeCycleAssessment.Compute.DepletionOfAbioticResources(BH.oM.Dimensional.IElementM, BH.oM.LifeCycleAssessment.MaterialFragments.IEnvironmentalProductDeclarationData)" : "This method has been removed as EvaluateEnvironmentalProductDeclaration contains the same functionality.",
```

2021-06-21 10:26 UTC, FraserGreenroyd commented on BHoMUpgrader42/Upgrades.json
> +      "BH.Engine.LifeCycleAssessment.Compute.DepletionOfAbioticResourcesFossilFuels": "This method has been removed as EvaluateEnvironmentalProductDeclaration contains the same functionality.",
```suggestion
      "BH.Engine.LifeCycleAssessment.Compute.DepletionOfAbioticResourcesFossilFuels(System.Double, System.Double, System.Double)" : "This method has been removed as EvaluateEnvironmentalProductDeclaration contains the same functionality.",
"BH.Engine.LifeCycleAssessment.Compute.DepletionOfAbioticResourcesFossilFuels(BH.oM.Dimensional.IElementM, BH.oM.LifeCycleAssessment.MaterialFragments.IEnvironmentalProductDeclarationData)" : "This method has been removed as EvaluateEnvironmentalProductDeclaration contains the same functionality.",
```

2021-06-21 10:26 UTC, FraserGreenroyd commented on BHoMUpgrader42/Upgrades.json
> +      "BH.Engine.LifeCycleAssessment.Compute.GlobalWarmingPotential": "This method has been removed as EvaluateEnvironmentalProductDeclaration contains the same functionality.",
```suggestion
     "BH.Engine.LifeCycleAssessment.Compute.GlobalWarmingPotential(System.Double, System.Double, System.Double)" : "This method has been removed as EvaluateEnvironmentalProductDeclaration contains the same functionality.",
"BH.Engine.LifeCycleAssessment.Compute.GlobalWarmingPotential(BH.oM.Dimensional.IElementM, BH.oM.LifeCycleAssessment.MaterialFragments.IEnvironmentalProductDeclarationData)" : "This method has been removed as EvaluateEnvironmentalProductDeclaration contains the same functionality.",
```

2021-06-21 10:26 UTC, FraserGreenroyd commented on BHoMUpgrader42/Upgrades.json
> +      "BH.Engine.LifeCycleAssessment.Compute.OzoneDepletionPotential": "This method has been removed as EvaluateEnvironmentalProductDeclaration contains the same functionality.",
```suggestion
      "BH.Engine.LifeCycleAssessment.Compute.OzoneDepletionPotential(System.Double, System.Double, System.Double)" : "This method has been removed as EvaluateEnvironmentalProductDeclaration contains the same functionality.",
"BH.Engine.LifeCycleAssessment.Compute.OzoneDepletionPotential(BH.oM.Dimensional.IElementM, BH.oM.LifeCycleAssessment.MaterialFragments.IEnvironmentalProductDeclarationData)" : "This method has been removed as EvaluateEnvironmentalProductDeclaration contains the same functionality.",
```

2021-06-21 10:26 UTC, FraserGreenroyd commented on BHoMUpgrader42/Upgrades.json
> +      "BH.Engine.LifeCycleAssessment.Compute.PhotochemicalOzoneCreationPotential": "This method has been removed as EvaluateEnvironmentalProductDeclaration contains the same functionality.",
```suggestion
      "BH.Engine.LifeCycleAssessment.Compute.PhotochemicalOzoneCreationPotential(System.Double, System.Double, System.Double)" : "This method has been removed as EvaluateEnvironmentalProductDeclaration contains the same functionality.",
"BH.Engine.LifeCycleAssessment.Compute.PhotochemicalOzoneCreationPotential(BH.oM.Dimensional.IElementM, BH.oM.LifeCycleAssessment.MaterialFragments.IEnvironmentalProductDeclarationData)" : "This method has been removed as EvaluateEnvironmentalProductDeclaration contains the same functionality.",
```

2021-06-21 10:27 UTC, FraserGreenroyd commented
@BHoMBot check versioning

2021-06-21 10:55 UTC, FraserGreenroyd requested changes

2021-06-21 10:55 UTC, FraserGreenroyd commented on BHoMUpgrader42/Upgrades.json
> +"BH.Engine.LifeCycleAssessment.Compute.AcidificationPotential(System.Double, System.Double, System.Double)", "This method has been removed as EvaluateEnvironmentalProductDeclaration contains the same
```suggestion
"BH.Engine.LifeCycleAssessment.Compute.AcidificationPotential(System.Double, System.Double, System.Double)": "This method has been removed as EvaluateEnvironmentalProductDeclaration contains the same functionality.",
```

2021-06-21 10:55 UTC, FraserGreenroyd commented
@BHoMBot check versioning

2021-06-21 14:44 UTC, FraserGreenroyd commented
@BHoMBot check versioning

2021-06-22 09:20 UTC, FraserGreenroyd commented
@BHoMBot check installer

2021-06-22 14:30 UTC, FraserGreenroyd commented
@BHoMBot check core

2021-06-22 14:30 UTC, FraserGreenroyd commented
@BHoMBot check copyright-compliance

2021-06-23 19:52 UTC, FraserGreenroyd commented
@BHoMBot check core

2021-06-23 20:17 UTC, FraserGreenroyd approved these changes
Functionality was tested by users via a PR artefact. Changes since have been for versioning, so these PRs are fit for merge with passing checks.

2021-06-23 20:23 UTC, merged