Upgrade CableTray
BHoM/Versioning_Toolkit pull request #170
Opened 2021-07-13 20:26 UTC by michaelhoehn

### NOTE: Depends on 

   
### Issues addressed by this PR

Closes #161 

### Test files

### Changelog

### Additional comments

2021-07-15 08:15 UTC, tiagogrossi approved these changes
Solution built and seems to be working as intended in a test script.

2021-07-19 18:52 UTC, michaelhoehn commented
@BHoMBot check core

2021-07-19 18:52 UTC, michaelhoehn commented
@BHoMBot check copyright compliance

2021-07-19 18:52 UTC, michaelhoehn commented
@BHoMBot check copyright-compliance

2021-07-19 19:27 UTC, michaelhoehn commented
@BHoMBot check core

2021-07-19 19:29 UTC, michaelhoehn commented
@BHoMBot check installer

2021-07-19 19:29 UTC, michaelhoehn commented
@BHoMBot check compliance

2021-07-19 21:18 UTC, michaelhoehn commented
@BHoMBot check versioning

2021-07-20 13:54 UTC, FraserGreenroyd requested changes
```
private static Dictionary<string, object> UpgradeCableTray(Dictionary<string, object> oldVersion)
        {
            if (oldVersion == null)
                return null;

            Dictionary<string, object> newVersion = new Dictionary<string, object>(oldVersion);

            if (newVersion.ContainsKey("ConnectionProperty"))
                newVersion.Remove("ConnectionProperty");

            return newVersion;
        }
```

I think this is all the method needs to contain given the changes on the object?

2021-07-20 13:54 UTC, FraserGreenroyd commented on BHoMUpgrader43/Converter.cs
> +                newVersion.Add("_t", "BH.oM.Geometry.Point");
I don't think this will do what you're expecting?

2021-07-20 13:54 UTC, FraserGreenroyd commented on BHoMUpgrader43/Converter.cs
> +                newVersion.Remove("ConnectionProperty");
I think this is the only bit we actually need?

2021-07-20 13:54 UTC, FraserGreenroyd commented on BHoMUpgrader43/Converter.cs
> +                newVersion.Add("SectionProperty", null);
This will overwrite any existing SectionProperty to be null

2021-07-20 13:54 UTC, FraserGreenroyd commented on BHoMUpgrader43/Converter.cs
> +                newVersion.Add("OrientationAngle", 0);
Likewise this will overwrite any existing OrientationAngle to be 0

2021-07-20 14:00 UTC, michaelhoehn commented
@BHoMBot check core

2021-07-20 14:06 UTC, FraserGreenroyd commented
@BHoMBot check versioning
@BHoMBot check installer

2021-07-20 14:21 UTC, FraserGreenroyd commented
@BHoMBot check copyright-compliance

2021-07-20 14:27 UTC, FraserGreenroyd approved these changes
Reviewed through with @michaelhoehn and all is good now.

2021-07-20 14:31 UTC, merged